# Generated by Django 2.1.4 on 2019-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amount_to_be_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='date_of_upload',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bedroms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
