# Generated by Django 2.1.4 on 2019-06-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_acres', models.CharField(blank=True, max_length=100, null=True)),
                ('property_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_search.Property')),
            ],
        ),
        migrations.CreateModel(
            name='OfficesBusinessAndStoreSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_square_feet', models.CharField(blank=True, max_length=100, null=True)),
                ('property_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_search.Property')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialBuildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.IntegerField(blank=True, null=True)),
                ('property_class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_search.Property')),
            ],
        ),
    ]
