# Generated by Django 2.1.4 on 2019-05-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0003_auto_20190523_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_bedroms',
            new_name='number_of_bedrooms',
        ),
    ]
