# Generated by Django 2.1.4 on 2019-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0005_auto_20190528_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='number_of_rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
